### ISSUE TITLE
Allow for custom data transfer mechanisms

### ISSUE THREAD

**Issue by MarcoPolo** [ipfs/helia#109]
Please correct me if I'm wrong, but it seems like bitswap is always activated if you provide a libp2p object to the [helia constructor](https://github.com/ipfs/helia/blob/main/packages/helia/src/helia.ts#L63). I would like a way to either:

1. Disable bitswap, and allow me to provide my own custom blockstore that may or may not use bitswap. If we do this it would be nice to expose the helia's [BlockStorage](https://github.com/ipfs/helia/blob/main/packages/helia/src/storage.ts#L28) so I can reuse that code with my own custom bitswap.
2. Allow for a custom bitswap to be passed in as an option (and maybe even allow for it to be set to false so it's disabled like 1).

I would like this so I can plug in alternative data transfer mechanisms like using the [HTTP gateway api](https://docs.ipfs.tech/reference/http/gateway/).

**Comment by BigLep** [comment]
@MarcoPolo : is this a duplicate of https://github.com/ipfs/helia/issues/98 ?

**Comment by MarcoPolo** [comment]
Yes, thanks. I didn't find that one. Closing in favor of the other one.

**Comment by SgtPooki** [comment]
@MarcoPolo This is now possible on the `helia@next` branch. pls let us know if you try it out.
