### ISSUE TITLE
@biglep 202305 feedback on Migration Guide and FAQ

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#120]
Below is some feedback on recent new wiki pages.  (Thanks for putting these together.)

Cross-cutting:
- ✅ Is it js-ipfs or js-IPFS?  I see we ware using "js-IPFS" in these new docs, but previously had seen it mostly written as "js-ipfs" (e.g., https://js.ipfs.tech/ )
   - Agreed to go with "js-IPFS"
- ✅ Idea: at least while these docs live in wiki, consider not having an inline TOC but rely on the autogenerated TOC that github wiki provides on the right-hand-side.  This is then less that someone needs to update.
   - Agreed to rely on wiki-generated TOCs.  The pages below have been updated.
- ✅ Update README calling out that there are more/other docs in the wiki.
   - https://github.com/ipfs/helia/pull/134

https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS
- Bitswap
   - ✅ Can we show the code snippet for what this looks like to get all the metrics?  I probably didn't poke around long enough, but this wasn't immediately jumping out to me from the links provided.
- Other
   - ✅ How does someone specify how Helia identifies itself (for libp2p identify and in the user-agent header when making HTTP calls)? Ideally we set “helia/vX.Y.Z” by default so we can properly identify its usage from DHT bootstrappers, cid.contact, etc.  Being tracked in https://github.com/ipfs/helia/issues/122
      - https://github.com/ipfs/helia/wiki/FAQ#-how-does-helia-identify-itself

https://github.com/ipfs/helia/wiki/FAQ
- Interop
  - ✅ Can we make a statement about https://github.com/ipfs/interop ?
     - https://github.com/ipfs/helia/wiki/FAQ#-how-does-helia-guarantee-compatibility-with-kubo-and-other-ipfs-implementations
- How does it perform compared to other implementations including js-IPFS?
  - ✅ Maybe link to your talk at IPFS Thing?
- What mechanisms does Helia have for content and peer routing?
  - ✅ We should drop @libp2p/delegated-content-routing and @libp2p/delegated-peer-routing right because that is basically promoting the Kubo RPC API?  I don’t think we want to be suggesting Helia users build applications on that.
     - https://github.com/ipfs/helia/wiki/FAQ#-what-mechanisms-does-helia-have-for-content-and-peer-routing
- Other
  - ✅ Remove https://github.com/ipfs/helia/blob/main/FAQ.md since it has been replaced here?
     - https://github.com/ipfs/helia/pull/134

**Comment by SgtPooki** [comment]
> Is it js-ipfs or js-IPFS? I see we ware using "js-IPFS" in these new docs, but previously had seen it mostly written as "js-ipfs" (e.g., https://js.ipfs.tech/ )

I've seen mostly only "js-ipfs", but ipfs is supposed to be "IPFS" so i've personally written "js-IPFS" myself a few times

> How does it perform compared to other implementations including js-IPFS?
> * Maybe link to your talk at IPFS Thing?

We should also link to benchmarks [source](https://github.com/ipfs/helia/tree/main/benchmarks/gc/src) and results

> * We should drop @libp2p/delegated-content-routing and @libp2p/delegated-peer-routing right because that is basically promoting the Kubo RPC API? I don’t think we want to be suggesting Heliausers build applications on that.

I agree that we shouldn't promote use of helia->kuboRPC.

**Comment by BigLep** [comment]
@achingbrain : a few things here:
1. It looks like we're going with "js-IPFS".  I don't have resolve to change it, so that seems fine to me.
2. I updated the issue description with the various things I have taken care of.  Some of these are dependent on https://github.com/ipfs/helia/pull/134
3. I did expand the wiki some: https://github.com/ipfs/helia/wiki
4. It would be great if you can take the other items so we can fully close this out.

**Comment by achingbrain** [comment]
> Is it js-ipfs or js-IPFS?

It's IPFS in the logo so I think it was supposed to be js-IPFS but js-ipfs crept in occasionally because it's slightly easier to type.

**Comment by achingbrain** [comment]
> Can we show the code snippet for what this looks like to get all the metrics? I probably didn't poke around long enough, but this wasn't immediately jumping out to me from the links provided.

I have updated this section to be more specific about using `@libp2p/prometheus-metrics`.  Hopefully it's clearer now.

**Comment by achingbrain** [comment]
> Can we make a statement about [ipfs/interop](https://github.com/ipfs/interop) ?

This is a module used for internal compatibility testing, it's not something used by Helia/js-IPFS users so this may confuse people?

We already have a general [FAQ about interop](https://github.com/ipfs/helia/wiki/FAQ#-how-does-helia-guarantee-compatibility-with-kubo-and-other-ipfs-implementations), maybe this is enough?

**Comment by achingbrain** [comment]
> How does it perform compared to other implementations including js-IPFS?
> > Maybe link to your talk at IPFS Thing?

Do you mean [this one](https://www.youtube.com/watch?v=zPeLYosZ3Ak)?  It was quite general, but I've linked to the section on garbage collection & pinning, hopefully that's better now.

**Comment by BigLep** [comment]
All items in the issue description have been completed.  I'm closing this issue.
