### ISSUE TITLE
Helia identifies itself to the network

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#122]
## Done Criteria
Helia identifies itself to the network by default.  Specifically this mean:
* libp2p identity - will be identifiable from DHT bootstrappers for example.  Kubo does this.
* user-agent header when making HTTP calls - This is relevant for example when making calls to cid.contact

We want to also get the Helia version as well (e.g., “helia/vX.Y.Z”) just as Kubo does.   

We should only set the "user agent" if a user hasn't specified an override one. 

## Why Important
This enables Helia's prevalence to be detected/measured.  This is important for getting signal on Helia's adoption in production, which in turn affects things like:
1. funding and resourcing decisions
2. client considerations for network/protocol upgrades

## Notes
1. At the end of this, problab should be able to generate the Helia equivalent of https://probelab.io/ipfsdht/#active-kubo-versions

**Comment by achingbrain** [comment]
> user-agent header when making HTTP calls

JS used to be forbidden from overriding `user-agent` in fetch requests - that changed with https://github.com/whatwg/fetch/issues/37

Firefox fixed it: https://bugzilla.mozilla.org/show_bug.cgi?id=1188932
Chromium has not fixed it: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

So currently this isn't possible with 90-odd% of browsers.

See CI failures in https://github.com/libp2p/js-ipni-content-routing/pull/12

**Comment by BigLep** [comment]
Thanks for the info @achingbrain .  So I think to close this issue we do two things:
1. Make sure it works for identify (which we can control)
2. Ensure the right info is being passed from Helia to js-libp2p so that HTTP content routings systems can pick this up in future.  (I assume this is done when number 1 above is done).
