### ISSUE TITLE
Wiki link formatting

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/helia#131]
I noticed that the headers for various [wiki](https://github.com/ipfs/helia/wiki) pages were recently changed to use emojis

<img width="318" alt="image" src="https://github.com/ipfs/helia/assets/113373882/cdf2d4b2-3cff-49b8-b136-8ea4b2b0ca57">

However, this means that links to pages now look like:
https://github.com/ipfs/helia/wiki/%E2%9D%93-FAQ
https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS

Also, this means that links like the ones below trigger the "GitHub wiki new page workflow" since this is technically a different link than the emoji-ed link:
https://github.com/ipfs/helia/wiki/FAQ
https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS

While the emojis do add a nice visual touch, this will probably cause some confusion when sharing links. Also thinking about linking into these docs from other doc sets like ipfs-docs, etc.

Suggestion:

Remove emojis from titles to avoid confusion, formatting issues, etc.

**Comment by BigLep** [comment]
Good point. This is my fault.  I'll fix it now.

**Comment by BigLep** [comment]
Fixed:
<img width="311" alt="image" src="https://github.com/ipfs/helia/assets/85411/303b7174-bedc-4771-8c84-b4927c70cbb7">
