### ISSUE TITLE
Unable to connect to ipfs cluster from helia node

### ISSUE THREAD

**Issue by logesh2496** [ipfs/helia#132]
I'm trying to create a helia browser node and trying to connect it to a ipfs cluster running in my local, but keep getting the below error 
> The dial request has no valid addresses

Provided the code below:

```
await createLibp2p({
  datastore,
  addresses: {
    listen: [],
    swarm: [
      '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star'
    ]
  },
  transports: [
    webRTC()
  ],
  connectionEncryption: [
    noise()
  ],
  streamMuxers: [
    yamux()
  ],
  services: {
    identify: identifyService()
  }
})
```

```
const heliaNode = await getHelia();
const addr = multiaddr("/ip4/127.0.0.1/tcp/9094");
heliaNode.libp2p.dial(addr) //Throws error
```

Thanks

**Comment by achingbrain** [comment]
> const addr = multiaddr("/ip4/127.0.0.1/tcp/9094");

You are dialing a tcp address here, but you've only specified a `webRTC` transport.  You need to add the [tcp transport](https://www.npmjs.com/package/@libp2p/tcp) to your list of transports to do this.

Please also check your libp2p config - there's no `swarm` key in the [addresses type](https://libp2p.github.io/js-libp2p/interfaces/index._internal_.AddressManagerInit.html) so this probably isn't doing what you think it's doing.

I also notice the swarm address contains a multiaddr for a webrtc star signalling server - the `@libp2p/webrtc-star` transport is deprecated and has been replaced with `@libp2p/webrtc` - it's better in that it doesn't require a signalling server - please see the [examples](https://github.com/libp2p/js-libp2p-webrtc/tree/main/examples) in that repo for how to use it.

**Comment by achingbrain** [comment]
The only transports a browser can use to dial another node are [WebSockets](https://www.npmjs.com/package/@libp2p/websockets), [WebTransport](https://www.npmjs.com/package/@libp2p/webtransport) and [WebRTC](https://www.npmjs.com/package/@libp2p/webrtc).  No other transports are available in browsers.

So your IPFS cluster needs to listen on a WebSocket, WebTransport or WebRTC address, then you will be able to dial it.

**Comment by achingbrain** [comment]
You can either dial the multiaddr like any other, or configure it as a bootstrap peer.

Something to consider is that WebRTC is only really intended for browser-to-browser communication.  If you're dialling something that isn't a browser, WebSockets or WebTransport is usually a better choice.

In general WebRTC has a number of drawbacks compared to WebSockets - it only runs in the UI thread, the packet size is limited to 16kb, it gets throttled if the current tab isn't active, etc.

To set it up as a bootstrap peer:

```js
import { webSockets } from '@libp2p/websockets'
import * as Filters from '@libp2p/websockets/filters'
import { bootstrap } from '@libp2p/bootstrap'

const libp2p = await createLibp2p({
  // ..other config
  transports: [
    webSockets({
      filter: Filters.all // this is necessary to dial local addresses using websockets
    })
    // other transports
  ],
  connectionGater: {
    denyDialMultiaddr: () => false // this is necessary to dial local addresses at all
  }
  peerDiscovery: [
    bootstrap({
      list: [
        `/ip4/127.0.0.1/tcp/${PORT}/ws/p2p/${PEER_ID}`
      ]
    })
  ]
})
```

You will have to substitute `PORT` and `PEER_ID` for whatever the values are.

**Comment by BigLep** [comment]
Maintainer note: we should create a wiki page around connectivity (ideally linking to js-libp2p docs).
