### ISSUE TITLE
helia/unixfs and helia/strings producing different results from same CID

### ISSUE THREAD

**Issue by deidyomega** [ipfs/helia#136]
```
import { createHelia } from "helia";
import { strings } from "@helia/strings";
import { MemoryDatastore } from "datastore-core";
import { MemoryBlockstore } from "blockstore-core";
import { unixfs } from "@helia/unixfs";
import { CID } from "multiformats/cid";
import util from "util";

const node = await createHelia({
  blockstore: new MemoryBlockstore(),
  datastore: new MemoryDatastore(),
});
const fs = unixfs(node);
const s = strings(node);
let cid = CID.parse("Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z");

console.log("strings.get implementation");
let val = await s.get(cid);
console.log(val);
console.log(util.inspect(val));

console.log("fs.cat implementation");
for await (const buf of fs.cat(cid)) {
  // console.info(buf);
  let val = new TextDecoder().decode(buf);
  console.log(val);
  console.log(util.inspect(val));
}

console.log("ctrl+c to exit");

```

Produces

```
strings.get implementation

☻↕Hello World!
↑
'\n\x14\b\x02\x12\x0EHello World!\r\n\x18\x0E'
fs.cat implementation
Hello World!

'Hello World!\r\n'
```

The question is, why does fs.cat and strings.get produce different results, and it appears as though they're different results on a binary level.

**Comment by achingbrain** [comment]
The CID is used to load a block from the blockstore or the network.

`@helia/strings` interprets the block as a unicode string encoded into a Uint8Array.

`@helia/unixfs` interprets the block as a UnixFS file and extract the data from it.

A [UnixFS](https://github.com/ipfs/specs/blob/main/UNIXFS.md) file is a binary structure wrapped in dag-pb and serialized using protobufs, so there's a bunch of extra binary around the strings, which is why you see all those garbage characters around the output of `@helia/strings` but not from `@helia/unixfs`.

**Comment by deidyomega** [comment]
So should I only use @helia/strings if I believe the cid came from a previously encoded @helia/strings system?

Or is it wise to just always use @helia/unixfs and grab the data directly (as it seems its a lot closer to the "real" value)

**Comment by achingbrain** [comment]
This is largely down to your application needs.

If the codec of the CID you're trying to read is a dag-pb, then it's almost certainly a UnixFS DAG and not a string:

```js
import { CID } from 'multiformats/cid'
import * as dagPB from '@ipld/dag-pb'

const cid = CID.parse('..string cid..')

if (cid.code === dagPB.code) {
  // do UnixFS things
} else {
  // do something else
}
```

if the codec is raw, it *might* be a string:

```js
import { CID } from 'multiformats/cid'
import * as raw from 'multiformats/codecs/raw'

const cid = CID.parse('..string cid..')

if (cid.code === raw.code) {
  // raw data, handle with care
} else {
  // do something else
}
```

If you're doing IPFS things, 99% of the time you're going to want to use `@helia/unixfs` for input and output and not `@helia/strings`.

**Comment by deidyomega** [comment]
When you say codec, it implies to me that you guys are compressing the file in some way. I had the assumption that the files never got compressed.

**Comment by achingbrain** [comment]
Your assumption is correct, nothing is compressed.

**Comment by deidyomega** [comment]
Okay, can you define codec in regard to IPFS?  Google says, "a device or program that compresses data to enable faster transmission and decompresses received data."  But you are saying you guys aren't compressing data.

**Comment by deidyomega** [comment]
I'm closing the  issue, regardless of what you mean by "codec" in ipfs/helia, @helia/unixfs does what I'm expecting it to do. Thanks for the input.
