### ISSUE TITLE
Improve bundler support

### ISSUE THREAD

**Issue by jeluard** [ipfs/helia#147]
Some bundler do not support `helia` due to a missing `main` attribute in `package.json`.

See more details [here](https://github.com/parcel-bundler/parcel/discussions/9077#discussioncomment-6109528).

**Comment by achingbrain** [comment]
Helia uses the exports map and not the legacy `main` field as you have found.

Looks like you also found out [how to turn on support for the exports map in Parcel](https://github.com/parcel-bundler/parcel/discussions/9077#discussioncomment-6109528), I'm glad they finally added support for this, though it does not appear to be [without bugs](https://github.com/parcel-bundler/parcel/issues/9078) for certain setups.

There's an [example of how to use Helia with Parcel here](https://github.com/ipfs-examples/helia-parcel) - these bundlers are able to bundle Helia so so I don't think there's anything else to do here.
