### ISSUE TITLE
Is there a way to use Infura's IPFS service using Helia?

### ISSUE THREAD

**Issue by maxdesalle** [ipfs/helia#157]
With `http-ipfs-client`, you could push data to Infura's IPFS servers. Is this still possible with Helia? If yes, how can this be done?

**Comment by Shubhaankar-Sharma** [comment]
yea i also wanted to know this, they deprecated http-ipfs-client so quick, but the migration to helia doesn't seem very clear

**Comment by achingbrain** [comment]
Helia is a fully-featured IPFS node, like js-IPFS before it, but it sounds like you're just using the RPC client to talk to remote Kubo nodes.

If you were previously using `ipfs-http-client` you should upgrade to [kubo-rpc-client](https://www.npmjs.com/package/kubo-rpc-client) - it's a drop-in replacement and where development is ongoing.

**Comment by YugasVasyl** [comment]
I have the same question. Any updates on it?

**Comment by achingbrain** [comment]
The question is answered above.  Please use [kubo-rpc-client](https://www.npmjs.com/package/kubo-rpc-client).
