### ISSUE TITLE
will helia support MFS?

### ISSUE THREAD

**Issue by resession** [ipfs/helia#158]
got used to using the Mutable File System files with js-ipfs

will helia support files/mfs like js-ipfs did?

**Comment by SgtPooki** [comment]
This discussion might be better suited for a post on https://discuss.ipfs.tech/c/help/helia/40

**Comment by achingbrain** [comment]
I put a quick MFS implementation together - check out the [API docs](https://ipfs.github.io/helia-mfs/modules.html).

By default it uses the same datastore key as `js-ipfs` so you should be able to load the MFS used by `js-ipfs` from the same repo if you need an upgrade path.

Please open any issues on the `@helia/mfs` repo - https://github.com/ipfs/helia-mfs

**Comment by BigLep** [comment]
@achingbrain : Thanks for creating.  I made an issue to track making sure the repo is easily discoverable: https://github.com/ipfs/helia-mfs/issues/3
