### ISSUE TITLE
Failed to establish a connection Error continuously showing in console

### ISSUE THREAD

**Issue by SachinCoder1** [ipfs/helia#165]
I am using chrome browser and Next JS 13.4.7 version with typescript.

And these our helia packages i am using:
 ` "helia": "^1.3.4",
 "@helia/json": "^1.0.0",
`

![image](https://github.com/ipfs/helia/assets/98685642/29429114-936a-4cb1-b739-4a810d22a3a8)

**Comment by SgtPooki** [comment]
see https://github.com/ipfs/helia/issues/151#issuecomment-1591437544 for an explanation about these errors. Please follow #151 for updates
