### ISSUE TITLE
Efficient directory import

### ISSUE THREAD

**Issue by achingbrain** [ipfs/helia#168]
The js-IPFS [glob source](https://github.com/ipfs/js-ipfs-utils/blob/master/src/files/glob-source.js) should be split out of js-ipfs-utils and published for use with Helia.

**Comment by SgtPooki** [comment]
Do we still need to do this considering globSource was used successfully in https://github.com/ipfs/helia/pull/171 ?

**Comment by achingbrain** [comment]
This is available in `@helia/unixfs@1.4.x` and later - https://github.com/ipfs/helia-unixfs/releases/tag/%40helia%2Funixfs-v1.4.0
