### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@helia/dag-cbor' imported from /home/akhil/Journey/Blockchain/JS/Office/ipfs/test.js

### ISSUE THREAD

**Issue by akhilparakka** [ipfs/helia#186]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@helia/dag-cbor' imported from /home/akhil/Journey/Blockchain/JS/Office/ipfs/test.js

**Comment by achingbrain** [comment]
Please can you share more information about your project setup, your dependencies and how you are loading the `@helia/dag-cbor` module?
