### ISSUE TITLE
Compatibility with Pinata and ipfs-core add?

### ISSUE THREAD

**Issue by buu700** [ipfs/helia#187]
I'm trying to migrate an existing code base to helia as a 1:1 replacement for ipfs-core, specifically from ipfs-core's `add` method. I have this mostly working by using `addBytes` from `@helia/unixfs` with the options `{cidVersion: 0, rawLeaves: false}`.

The problem is that this seems to break when the buffer is longer than the default chunk size / shard split threshold of 262144 bytes. The CID v0 strings I'm getting back are different than expected. Is there an option I'm missing that will restore the legacy behavior, or am I stuck using the older library for the time being?

Edit: I was initially trying to do this in two steps, but upgrading to CID v1 at the same time is probably fine. However, I'm running into the same issue with CID v1.

More directly, the problem is that the string doesn't match what I'm getting back from the Pinata pinning API. Modifying `shardSplitThresholdBytes` doesn't seem to affect the CID string at all, so maybe there's a bug that causes that option to be ignored?

**Comment by achingbrain** [comment]
`@helia/unixfs` uses a different set of default importer options, it's aligned with Filecoin rather than Kubo.

You can simulate the Kubo import settings with [these options](https://github.com/ipfs/helia-unixfs/blob/main/packages/interop/test/files.spec.ts#L34-L42) - hopefully that helps.

**Comment by buu700** [comment]
Really sorry about the late reply @achingbrain and @SgtPooki! Thanks a lot for getting back to me! I'd meant to test it out and get back to you earlier, but that looks like exactly what I was looking for, and I'll follow up as soon as I confirm that it's 100% working for me.

Related: https://github.com/cyph/cyph/issues/78
