### ISSUE TITLE
vulrnarbility in js-libp2p-gossipsub

### ISSUE THREAD

**Issue by syonfox** [ipfs/helia#191]
https://github.com/ChainSafe/js-libp2p-gossipsub/issues/453#issuecomment-1657273937 

Hey just wondering if this is fixed and if we can publish npm. 

```[tasklist]
### Tasks
```

**Comment by syonfox** [comment]
fore more detail this is present in curent esbuild example

**Comment by achingbrain** [comment]
The issue you've linked to on the gossipsub repo has the latest status, Helia will ship with an updated version of gossipsub when it is available.
