### ISSUE TITLE
How does Helia link to an existing IPFS private network?

### ISSUE THREAD

**Issue by HX2012** [ipfs/helia#212]
I have created a private network for IPFS with Swarm.Key. Now I need to use Helia to connect to it. What should I do?

**Comment by achingbrain** [comment]
Configure libp2p with your private key, eg:

```js
import { createHelia } from 'helia'
import { preSharedKey } from 'libp2p/pnet'

const node = await createHelia({
  libp2p: {
    connectionProtector: preSharedKey({
      psk: swarmKey
    })
  }
})
```

`swarmKey` is a `Uint8Array` that contains your swarm key.

See the [pnet libp2p example](https://github.com/libp2p/js-libp2p/tree/master/examples/pnet) for more.

**Comment by HX2012** [comment]
I truly appreciate your timely help.

**Comment by Arlodotexe** [comment]
> See the [pnet libp2p example](https://github.com/libp2p/js-libp2p/tree/master/examples/pnet) for more.

@achingbrain link is dead
