### ISSUE TITLE
Does Helia support connecting to remote infura node ?

### ISSUE THREAD

**Issue by pranav-singhal** [ipfs/helia#265]
I cannot seem to find any documentation regarding trying to connect to a infura node with helia. Is that supported?

**Comment by achingbrain** [comment]
If you are trying to dial the multiaddr of an infura IPFS node, then yes, it is supported.

If you are trying to use Helia where you previously used [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client) then no, you should use [kubo-rpc-client](https://www.npmjs.com/package/kubo-rpc-client) instead.

Can you please share more details of what you are trying to do?
