### ISSUE TITLE
Update landing page to show to a non-node how to start

### ISSUE THREAD

**Issue by icemagno** [ipfs/helia#269]
You start your "how-to" this way:

```
TO USE HELIA TRY THIS:

import { createHelia } from 'helia'
import { strings } from '@helia/strings'

const helia = await createHelia()
const s = strings(helia)

const myImmutableAddress = await s.add('hello world')

console.log(await s.get(myImmutableAddress))
// hello world
```

Ok.... but what do I need to do BEFORE this  ????

Don't make assumptions about others' knowledge when creating a manual. 
Always treat your reader as if they were just born

**Comment by bthornemail** [comment]
Nothing. There is a default config in the code that is run. It's runnable code

**Comment by 2color** [comment]
Thanks for sharing this feedback, @icemagno. I agree that we shouldn't make too many assumptions about the reader when writing docs and READMEs. 

Either way, Helia might be too low-level for your use case. If you are trying to share files in a private network, you might want to look more of a turnkey solution like [Kubo](https://github.com/ipfs/kubo) or [Iroh's Sendme](https://iroh.computer/sendme) (note that they aren't interoprable) 

Helia is a library/sdk. You can build an API on top of it and use it for file sharing, but it will require putting together a number of pieces to make it work.
