### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by christroutner** [ipfs/helia#279]
I'm running commit bb94efc from the `main` branch. I installed dependencies with `npm install`, then ran `npm test`. The tests fail with this error:

- `Cannot find module '@helia/interface' or its corresponding type declarations.`

I'm running node v18.12.1 and npm v8.19.2.

Even after running `npm install @helia/interface`, I get the same errors.

I'm sure I'm not the only one that would like to know how to run tests on this repository. Can someone provide guidance?

I'm primarily interested in a node.js environment. I got the same errors when trying to run `npm run test:node`.

**Comment by achingbrain** [comment]
You need to run `npm run build` from the root of the repo first.  After that you can run tests in individual packages, or in all of them from the root.
