### ISSUE TITLE
Can't connect to IPFS network (with port forwarding)

### ISSUE THREAD

**Issue by PedroBarcha** [ipfs/helia#295]
Hi everyone! I've been trying to connect to the IPFS network using Helia, but haven't been sucessful :(

Could you plese help me?

I have just made a port forwarding (4001) and tried connecting to the IPFS using kubo. With that, I have succesfully served content to the network. Now I am trying to do the same with Helia. From what I've understood, I don't need kubo anymore, since Helia should create a node for me right? **So I have killed the kubo instance** and tried the following code:

![image](https://github.com/ipfs-examples/helia-examples/assets/11379168/3f884584-ade8-40bd-bc3e-7588f7bb7a9f)

The output is:
```
Peer ID:  PeerId(12D3KooWQrrNc6wmWwCZQRtsTtPiaAXyM8B8wxgDh8mzn84CdUiG)
getPeers:  []
Multiaddrs: [
  Multiaddr(/ip4/127.0.0.1/tcp/4001/p2p/12D3KooWQrrNc6wmWwCZQRtsTtPiaAXyM8B8wxgDh8mzn84CdUiG),
  Multiaddr(/ip4/192.168.15.19/tcp/4001/p2p/12D3KooWQrrNc6wmWwCZQRtsTtPiaAXyM8B8wxgDh8mzn84CdUiG),
  Multiaddr(/ip4/172.26.0.1/tcp/4001/p2p/12D3KooWQrrNc6wmWwCZQRtsTtPiaAXyM8B8wxgDh8mzn84CdUiG),
  Multiaddr(/ip4/172.27.0.1/tcp/4001/p2p/12D3KooWQrrNc6wmWwCZQRtsTtPiaAXyM8B8wxgDh8mzn84CdUiG)
]
```

As you can see, I am not getting anything with `helia.libp2p.getPeers()`. Also, my peer isn't found when trying to use https://pl-diagnose.on.fleek.com:

![image](https://github.com/ipfs-examples/helia-examples/assets/11379168/31b0c36e-30ca-44da-9974-48a5748ecdc0)

Moreover, if if try to add some content, it doesn't get published to the IPFS network.

I suspect that my configuration isn't correct, could anyone check it, please? Also, am I right to assume that Helia will create a node that can connect to the IPFS network?

Finally, I'd like to say  that Helia rocks 🤘. I managed to do all I need locally (publish, pin, MFS, IPNS...),  the only thing I need now is to fix this. Thanks in advance!

**Comment by MichaelJCole** [comment]
Hi Pedro, I'm also having this problem, did you find a solution?

I worked for a couple days on my own libp2p instance before checking the code in Helia.  Here are the defaults for Helia in browser and desktop:  https://github.com/ipfs/helia/tree/main/packages/helia/src/utils

Even using the default Helia, I'm still having trouble finding my CIDs here https://check.ipfs.network

**Comment by SgtPooki** [comment]
@PedroBarcha Thanks for including a screenshot of your code. 

Your config is missing a few things. 


> As you can see, I am not getting anything with helia.libp2p.getPeers()

You will need to wait a bit for connections to occur. You can set listeners to monitor when peers are discovered, connected, and disconnected. See https://libp2p.github.io/js-libp2p/interfaces/_libp2p_interface.index.Libp2pEvents.html for event types

> Also, my peer isn't found when trying to use [pl-diagnose.on.fleek.com](https://pl-diagnose.on.fleek.com/):

You are not enabling the DHT service. see https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/libp2p-defaults.ts for a config that enables the DHT

> Also, am I right to assume that Helia will create a node that can connect to the IPFS network?

Yes, by default, a helia node has a minimum number of connections it tries to keep open (default config from libp2p). It will attempt to remain connected to your closest peers on the network.

---

@MichaelJCole it seems like the issue you're running into differs from the one @PedroBarcha mentioned, but may be related to not having any peers connected. Make sure you can find your peer on the DHT using https://pl-diagnose.on.fleek.co/, and then test that someone is serving the CIDs
