### ISSUE TITLE
Name this project

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#3]
## What

IPFS Stewards are choosing a name for this project. As explained in https://github.com/ipfs/ipfs/issues/470, the name will not include "IPFS".

We are using the placeholder "Pomegranate" name for now. We are now having a vote for a new name. The initial brainstorm & vote for a new name was held during IPFS Camp 2022.

Note: we reserve the right to ignore every instance of [Boaty McBoatface](https://en.wikipedia.org/wiki/Boaty_McBoatface).

> :point_right: Feel free to comment in https://github.com/ipfs/ipfs/discussions/495 with a name (and, if possible, a logo).

## Why

This is part of a wider ecosystem epic (https://github.com/ipfs/ipfs/issues/470) where we clarify that IPFS is a set of interoperable protocols and conventions, and not a specific implementation.

- This project won't use the "IPFS" name.
- We want to encourage others to create their own implementations.
- A unique name makes it easier to think in terms of "IPFS protocol, libraries and specs" and "IPFS implementations".

## When

As mentioned above, we are now [collecting name ideas](https://github.com/ipfs/ipfs/discussions/495). See that discussion for details.

###  :green_circle:  Where to put the new name:

Immediate:
- [x] README and docs
- [x] Git repo name
- [x] npm package

Additional items once this project ships will be tackled in https://github.com/ipfs/pomegranate/issues/4

----

## WANT TO PROPOSE A NEW NAME?

:point_right: Feel free to comment in https://github.com/ipfs/ipfs/discussions/495 with a name (and, if possible, a logo).

**Comment by tinytb** [comment]
We are now gathering name proposals here:
- https://github.com/ipfs/ipfs/discussions/495

**Comment by tinytb** [comment]
This project has been named **[Helia](https://github.com/ipfs/helia)** 🎉

**Comment by M3g4Kn1ght** [comment]
I need help when i download helia there is a vulnerability with semver, how can i solve it?
