### ISSUE TITLE
NextJS example failed to establish connection error

### ISSUE THREAD

**Issue by ale-ben** [ipfs/helia#308]
I tried cloning and running the helia next example (https://github.com/ipfs-examples/helia-examples/tree/8cf69374b18c17e8b6ca16aa6df6adab7f24d4c4/examples/helia-nextjs).

As seen in the image below, the ID and status seem to work but on the console a lot of connection errors appear.
I don't have libp2p as a dependency in my package.json so this is a dependency of Helia.
Should I open a ticket on the libp2p repo?

Note that I tried recreating the project from scratch, as soon as you add `const heliaNode = await createHelia()`, the errors appear, therefore it is not a problem with the example code.

<img width="754" alt="Screenshot 2023-11-09 at 11 42 07" src="https://github.com/ipfs/helia/assets/17771264/2cafbf03-c202-4e00-965d-44faa9c641b7">

This is my package.json
```
{
  "name": "helia-nextjs",
  "version": "1.0.0",
  "description": "Using Helia with nextjs",
  "private": true,
  "type": "module",
  "scripts": {
    "clean": "rimraf ./dist ./.next",
    "dev": "next dev",
    "build": "next build && next export -o dist",
    "serve": "npm run dev",
    "start": "next start",
    "lint": "next lint",
    "test": "npm run build && test-browser-example test"
  },
  "dependencies": {
    "helia": "^2.1.0",
    "next": "^14.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@playwright/test": "^1.32.1",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.2.4",
    "interface-datastore": "^8.2.0",
    "playwright": "^1.32.1",
    "rimraf": "^5.0.0",
    "test-ipfs-example": "^1.0.0"
  }
}

```

**Comment by SgtPooki** [comment]
These connection errors are normal in the browser space. Please see https://github.com/ipfs/helia/wiki/Troubleshooting#-im-seeing-a-lot-of-errors-in-my-browser-console-when-using-helia-how-can-we-catch-and-handle-these-errors for more information.
