### ISSUE TITLE
Process does not terminate after calling stop()

### ISSUE THREAD

**Issue by Flamenco** [ipfs/helia#309]
# Issue

I am trying to shutdown my node by calling `await helia.stop()`, but there are still active timers and listening ports that prevent the process from terminating. 

# Workaround
call `process.exit(0)`

Another strategy that worked was to call `gc()` before `stop()`.  Perhaps `stop()` should call `gc()` internally...
```js
await helia.gc()
await helia.stop()
```

# More Information
For your debugging pleasure I am including a dump of open items

```text
open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
  - fd 0 (tty)
- Sockets:
  - 2600:4040:5b06:f300:7c33:3c4f:8cc3:26cf:52501 -> 2602:fea2:2::1:443
- Servers:
  - <unknown address>
    - Listeners:
      - connection: bound onSocket @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/@libp2p/tcp/src/listener.ts:88
  - <unknown address>
    - Listeners:
      - connection: bound onSocket @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/@libp2p/tcp/src/listener.ts:88
- Timers:
  - (5000 ~ 5 s) (anonymous) @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/libp2p/src/connection-manager/auto-dial.ts:107
  - (10000 ~ 10 s) (anonymous) @ node:internal/deps/undici/undici:8364
  - (100 ~ 100 ms) runHeartbeat @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:598
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
  - (2000 ~ 2 s) (anonymous) @ unknown:0
  - (1000 ~ 1000 ms) later @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/libp2p/src/address-manager/utils.ts:11
  - (84600000 ~ 23 hr) (anonymous) @ file:///Users/steven/dev/projects/ct/ct-labs/projects/helia-test/node_modules/p-timeout/index.js:72
```

**Comment by tuler** [comment]
Im also experiencing this, and calling `gc` didn’t help

**Comment by achingbrain** [comment]
Calling gc is almost certainly a red herring here, all that's going to do is delete any un-pinned blocks from your blockstore, it's not going to affect open TCP sockets.

The reported issue sounds similar to https://github.com/ChainSafe/lodestar/issues/6053 which in turn seemed to be related to https://github.com/libp2p/js-libp2p/pull/2058

That went out in `@libp2p/tcp@8.0.8` - do you still see the issue if you use `@libp2p/tcp@8.0.7` - if not we should probably revert that change.

**Comment by Flamenco** [comment]
Not planning on fixing a resource leak?  Hmmmm.

**Comment by nflaig** [comment]
> The reported issue sounds similar to https://github.com/ChainSafe/lodestar/issues/6053 which in turn seemed to be related to https://github.com/libp2p/js-libp2p/pull/2058

This is a different issue, see https://github.com/ChainSafe/lodestar/issues/5642. Since we are running libp2p in a `worker_thread` now I can't tell if this is still there but seems related to https://github.com/ChainSafe/lodestar/issues/5775 which is even more problematic.

**Comment by SgtPooki** [comment]
> Not planning on fixing a resource leak? Hmmmm.

Normally this issue would be closed as stale because lack of author response. if you have response or remaining concerns, we'd be happy to look into it.
