### ISSUE TITLE
Have public coordination channel across chat platforms

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#33]
## Done Criteria
There is a README-documented channel across chat platforms for coordinating contributions to Helia.

## Why Important
Lower the barrier to entry for potential contributors to get involved and get there questions answered so they can contribute. 

## User/Customer
Would-be and current Helia contributors.

## Notes
Right now there is #ip-js in Filecoin Slack.  While PL EngRes lives there, it doesn't seem ideal to require other Helia contributors to join Filecoin slack to engage.  Ideally we bridge that channel (or another/new channel like #helia) to ipfs.io Matrix and IPFS Discord.  

The README should be updated as a result.

**Comment by SgtPooki** [comment]
Helia WG 2024-08-15:

* slack is very noisy.. ip-js has a lot of non helia stuff.. not linkable
* discuss.ipfs.tech - hard to get folks to adopt, cross impl, etc.
* github discussions: we should use this.. try it out.

done criteria: use github discussions

**Comment by SgtPooki** [comment]
github discussions are open. please bring your questions and non-bug reports there: https://github.com/ipfs/helia/discussions
