### ISSUE TITLE
Helia v3 Release

### ISSUE THREAD

**Issue by achingbrain** [ipfs/helia#337]
Welcome to the tracking issue for the next major Helia release!

The main feature is the upgrade to libp2p@v1.  This is a significant upgrade with lots of performance work having been done.  In terms of streaming performance, js-libp2p is now the fastest libp2p implementation - https://observablehq.com/@libp2p-workspace/performance-dashboard

Unfortunately the API has changed and Helia exposes the underlying libp2p node so it has to go out as a major.

This gives us a nice opportunity to include the iterable pinning PR that's been sitting in the input queue for a little while - it lets the user control the concurrency of pinning as with other iterables and will eventually allow users to pick up on a failed pinning operation where they left off.

- [x] Upgrade libp2p to v1 - https://github.com/ipfs/helia/pull/320
- [x] Iterable pinning - https://github.com/ipfs/helia/pull/231
- [x] Upgrade guide

**Comment by maceip** [comment]
<img width="350" alt="1.0" src="https://github.com/ipfs/helia/assets/804368/b0908ff1-4178-4f6f-919c-3e6e769ce86f">

  🔥

**Comment by SgtPooki** [comment]
@achingbrain some potential items we may want to add for v3:

* https://github.com/ipfs/helia/pull/342
* https://github.com/ipfs/js-ipfs-bitswap/issues/604
* https://github.com/ipfs/helia/issues/289
* https://github.com/ipfs/helia/issues/344
