### ISSUE TITLE
feat: create @helia/block-brokers package

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#341]
Break out blockBrokers (at least trustless gateways) from helia so things like https://github.com/meandavejustice/trustless-gateway-fetch and https://github.com/ipfs/helia/issues/289 can consume it more easily.

For now, should be inside this main repo

some discussion held in slack at https://filecoinproject.slack.com/archives/C046HDAHA13/p1702058245269949

**Comment by meandavejustice** [comment]
@SgtPooki Can you assign this to me?

**Comment by meandavejustice** [comment]
Open questions here:

- Do we need to still do browsers tests here?
- `default-hashers.ts` is now used in multiple places. Its a small file, so probably fine to duplicate, but might make sense to pull into a `@helia/utils` package as things change.

**Comment by SgtPooki** [comment]
I believe this is done now
