### ISSUE TITLE
Trustless gateway broker should use subdomain gateway to prevent 301 roundtrips

### ISSUE THREAD

**Issue by 2color** [ipfs/helia#347]
## Background

The current Trustless gateway broker uses path resolution by default and has 4 subdomain gateways defined in the defaults. This leads to it getting 301s for most requests because subdomain gateways redirect from path requests to the subdomain. For example: 

```
https://cf-ipfs.com/ipfs/QmTUAobz6YU1Ej5dTibodQPNtKk2TNnQek5TXHv13Dk2zq?format=raw -> 301 https://bafybeicmg6dvbhclp6sctn7nfhaex64x7fuw552cufodvjt56zispmvhoy.ipfs.cf-ipfs.com/

https://dweb.link/ipfs/QmRCKiUi5g4w4QBpyNkTiczrcTiwQtGK9DHLnncxXdfD7c?format=raw -> 301 https://bafybeibkodyc2gs43vfj4cond2tw2kb4qsuik72bmeij5dpvwiyvsfasl4.ipfs.dweb.link/?format=raw
```

Since 301s are permanent, the browser will cache these after the initial request, however, this results in an additional round trip per CID.

https://github.com/ipfs/helia/blob/299bb0942bbfae492db938c4ccad4e835bab2dbd/packages/helia/src/block-brokers/trustless-gateway/trustless-gateway.ts#L48-L53

## Suggested solutions

- By default, use subdomain gateway URLs to fetch blocks in the gateway broker.
- Use path gateways
- Maybe make the gateway broker aware of whether a gateway supports subdomain resolution, [since some of the public trustless gateways don't support subdomain resolution](https://ipfs.github.io/public-gateway-checker/)

**Comment by SgtPooki** [comment]
I think we should use attempt to use subdomain gateways, and convert any cidv0 to v1

**Comment by 2color** [comment]
One thing to consider is that not all gateways support subdomain resolution. If we only support subdomain gateways we're limiting users because they are less common. If we support both, it comes with the added complexity (which seems fine).

I realise that subdomain resolution is important for origin isolation, but only relevant for loading sites directly from the trustless gateway.
