### ISSUE TITLE
@helia/interface and @helia/interop don't generate /dist folder on install (in monorepo)

### ISSUE THREAD

**Issue by meandavejustice** [ipfs/helia#353]
`/dist` should be generated with compiled js files for depending packages to be able to consume the library. It looks like they are not properly being generated on `npm install`

![image](https://github.com/ipfs/helia/assets/1844554/60006a48-7968-44b4-9423-5324e1dc0683)

**Comment by meandavejustice** [comment]
This actually seems to only happen within the helia monorepo. The `/dist` directory is created correctly when installing as a dependency of another package 🤔

**Comment by SgtPooki** [comment]
I believe the dist folder should only be created during the `build` step.

**Comment by meandavejustice** [comment]
We can close this, I think I was having issues with my local machine
