### ISSUE TITLE
bug: race condition in @helia/ipns->dns resolvers->default should abort if signal is aborted

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#385]
`default should abort if signal is aborted` failed during a job: https://github.com/ipfs/helia/actions/runs/7545440173/job/20541106692?pr=384#step:5:141

```sh
@helia/ipns: npm run test:chrome-webworker
# ...
@helia/ipns:   1) dns resolvers
@helia/ipns:        default should abort if signal is aborted:
@helia/ipns:      AssertionError: expected promise to be rejected but it was fulfilled with '/ipfs/QmVAvbnR2M7jTPfU3fQK12VfYPYqcGJ…'
```

assuming it's a race condition because re-run succeeded: https://github.com/ipfs/helia/actions/runs/7545440173/job/20548725299?pr=384

**Comment by acul71** [comment]
Couldn't pinpoint the exact test. 
Links contain partial content.
