### ISSUE TITLE
version incompatability

### ISSUE THREAD

**Issue by laksh-1052** [ipfs/helia#404]
i was using node16.0.0 can you please help me out which version of helia to use?
node:internal/modules/cjs/loader:483
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

i keep getting this error

**Comment by vmx** [comment]
It sounds like you're trying to import Helia via CommonJS. See https://github.com/ipfs/helia/wiki/Troubleshooting#%EF%B8%8F-i-am-getting-err_require_esm-or-err_package_path_not_exported-errors for more information.

**Comment by achingbrain** [comment]
@vmx is correct, please use `import` to load Helia - see the linked wiki page for more information.
