### ISSUE TITLE
Establish mechanism for usage / adoption monitoring

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#41]
## Done Criteria
We have a mechanism that highlights on a ~monthly basis if/who is using Helia.  We can see month-over-month growth, can see who started/stopped using Helia in a given month, and can annotate any notes about usage.

## Why Important
We want to make sure we're focused on adoption.  No/slow growth is a signal.  Knowing who is using it is important for understanding user needs better. 

## Notes
For seeing which packages are depending, there are different tools including:
- https://github.com/ipfs/helia/network/dependents

We can look at things like downloads (e.g., https://npm-stat.com/charts.html?package=helia&package=helia-examples&package=helia-ipns&package=helia-unixfs&from=2023-01-01&to=2023-06-30 ), but that isn't very useful right now.  Knowing specific dependencies is more interesting.

One process would be to monthly as part of PL EngRes All Hands prep to take the latest dependent list, and in a spreadsheet, highlight anyone new, and potentially followup.

**Comment by SgtPooki** [comment]
I'm closing this due to changes in the maintainers' organization. 

https://ipshipyard.com/ is the primary maintainer of this package and others now. We currently don't have the facility to monitor and track this, but we can come back to it if/when appropriate.
