### ISSUE TITLE
Creating Helia in nextjs fails with "TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<Bootstrap>'"

### ISSUE THREAD

**Issue by ianconsolata** [ipfs/helia#424]
This error happened in both Typescript and Javascript. 
![Screenshot 2024-02-08 at 2 20 34 PM](https://github.com/ipfs/helia/assets/405465/90195892-5550-45e2-ba53-6212e1df47f6).

I am using the sample code from the Helia examples repo in a different project. When I tried to run the example repo directly, I got a different error: https://github.com/ipfs-examples/helia-examples/issues/289

**Comment by ianconsolata** [comment]
I just reran my sample repo, and downgrading to `14.0.4` resolved the issue for me. Sounds like this issue and https://github.com/ipfs-examples/helia-examples/issues/289 might have the same root cause.

**Comment by achingbrain** [comment]
Nextjs had a regression but it was fixed in v14.1.3.

Please reopen this issue if you are still having problems.
