### ISSUE TITLE
React-native support?

### ISSUE THREAD

**Issue by sleep9** [ipfs/helia#435]
```
const node = await createNode(relayAddrs,pid); // libp2p
 const datastore = new MemoryDatastore()
 const ipfs = await createHelia({ datastore,libp2p:node }) 

```

Getting the following error when trying to create an instance of helia. 
"Your javascript code tried to access a native module that doesnt exist in this development client"

Maybe someone can reproduce this error. Not sure what needs to be polyfilled or what native library is needed.
Tried rm -rf ./node_modules, npm install, pod deintegrate && pod install but no luck. 
Tried "postinstall": "rn-nodeify --install events --hack" no luck.

**Comment by achingbrain** [comment]
There are some polyfills/config that need to be set up to modernise the React Native environment - it's documented here - https://github.com/ipfs-shipyard/js-libp2p-react-native

Could you try building from that project, then adding Helia to it to see what extra stuff is needed?

**Comment by sleep9** [comment]
I started from a git clone of that repository. Here is the error, I thought it might be events but I was wrong.

<img width="367" alt="Screenshot 2024-02-15 at 09 33 22" src="https://github.com/ipfs/helia/assets/60583270/9eadd696-943c-4049-ac93-a8c5e6fda680">

**Comment by sleep9** [comment]
The native module required was react-native-webrtc.
