### ISSUE TITLE
Helia incompatible with latest js-stores datastores

### ISSUE THREAD

**Issue by leblowl** [ipfs/helia#585]
Due to https://github.com/ipfs/js-stores/pull/315, it appears that any code like this is currently incompatible: https://github.com/ipfs/helia/blob/ac4bdb8a73cab23500221340830969552a1d8db6/packages/utils/src/pins.ts#L157

For now, if you are using Helia 4.2.5 and Level (for example), it looks like datastore-level < 11.0.0 is required

**Comment by SgtPooki** [comment]
@leblowl FYI: libp2p2.0 is coming soon and will also be changing error codes from `.code` to `.name` so we will likely not have this change out in a new Helia release until we can bring them both in

**Comment by achingbrain** [comment]
The `.code` property was re-added to the js-stores implementations by https://github.com/ipfs/js-stores/pull/320 so this issue should be fixed now.  Sorry for the disruption.

The next Helia release will switch to using the `.name` property anyway but things are backwards compatible now.

**Comment by achingbrain** [comment]
I'm going to close this issue, please re-open it if you're still having problems.
