### ISSUE TITLE
Resource (staffing) options

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia#6]
## Purpose
This issue serves as a pointer to various ways that one can help resource/staff this project to accelerate its development.  For example, blog posts, social media, etc. link to this issue which we in turn update with the latest info and options.

## Background
At least as of 2022-10-27, the biggest thing holding back this IPFS implementation from being delivered and released is developer resources.  Per the [roadmap](https://github.com/ipfs/pomegranate/issues/5), a key focus for the remainder of 2022 is to increase the staffing so we can make this project a reality and have impact.

## Options
1. 🫂 Join the core/maintainer team as a contractor or full-time employee - [Protocol Labs' Engineering and Research group](https://pl-strflt.notion.site/PL-EngRes-Public-b5086aea86ed4f81bc7d0721c6935e1e), which is initiating this effort, is hiring and needs more JavaScript and TypeScript developers who are eager to make this project a reality. It’s ideal if you have experience working at the protocol/bytes/streams level. Please apply [here](https://boards.greenhouse.io/protocollabs/jobs/4416822004).
2. ✋ Contribute - Open source contributors welcome. Do you have a great idea for a part you could own and need some funding? Consider a [grant request](https://github.com/ipfs/devgrants).

**Comment by SgtPooki** [comment]
we should link any "grant" or application links, when relevant, to #82
