### ISSUE TITLE
Need a way to restart the node so that the peerId and content addresses are not lost

### ISSUE THREAD

**Issue by 25x8** [ipfs/helia#671]
There is no way to restart the node without generating a new peerId.
There is a need for such a mechanism, which is particularly relevant for private networks.

**Comment by tabcat** [comment]
Hello @25x8,

This is likely due to the PeerId and content being stored in memory by default (MemoryDatastore). Another datastore with a non-volatile storage backend can be passed an an option to the createHelia function.

**Comment by tabcat** [comment]
Some datastore implementations can be found here: https://github.com/ipfs/js-stores
