### ISSUE TITLE
Tracking Issue: IPFS Camp 2022 presentation

### ISSUE THREAD

**Issue by tinytb** [ipfs/helia#7]
Per https://github.com/ipfs/pomegranate/pull/1#discussion_r1006217455, this is a tracking issue for the IPFS Camp 2022 presentation by @achingbrain. This issue will be updated with a link to the presentation, when available.

**Comment by achingbrain** [comment]
The presentation is here: https://github.com/achingbrain/state-of-ipfs-in-js-2022-talk

**Comment by achingbrain** [comment]
Video is here: https://www.youtube.com/watch?v=4BPah-xItxA
